apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
  volumes:
  - name: fabricfiles
    persistentVolumeClaim:
      claimName: fabric-pvc
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:2.0.0
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48h"]
      env:
      - name: GODEBUG
        value: netdns=go
      - name: CORE_VM_ENDPOINT
        value: unix:///host/var/run/docker.sock
      - name: TZ
        value: "Europe/Brussels"
      - name: FABRIC_CFG_PATH
        value: /fabric
      - name: CORE_PEER_TLS_ENABLED
        value: "false"
      - name: CORE_PEER_TLS_CLIENTAUTHREQUIRED
        value: "false"
      volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
        - mountPath: /host/var/run/docker.sock
          name: dockersocket