---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pv
  labels:
    type: nfs
    name: fabricfiles
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.64.1
    path: /Users/jonathan/nfs/fabric
    readOnly: false