apiVersion: v1
kind: Service
metadata:
  name: peer0-org2-example-com
  labels:
    run: peer0-org2-example-com
spec:
  type: ClusterIP
  selector:
    name: peer0-org2-example-com
  ports:
  - protocol: TCP
    port: 9051
    name: grpc