# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: example-com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        CommonName: orderer-example-com
    CA:
      Hostname: ca
      CommonName: "ca-example-com"