# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

PeerOrgs:
  - Name: Org1
    Domain: org1-example-com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        CommonName: peer0-org1-example-com
    CA:
      Hostname: ca
      CommonName: "ca-org1-example-com"
    Users:
      Count: 1
